package dev.robin.privacify.ui.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFF14B8A6)

val AutoGuardPrimary = Color(0xFF7C3AED)
val AutoGuardSecondary = Color(0xFFA855F7)
val AutoGuardGlow = Color(0xFFC084FC)

val LockdownRed = Color(0xFFDC2626)
val LockdownRedDark = Color(0xFF991B1B)

val GreenVibrant = Color(0xFF10B981)
val GreenVibrantDark = Color(0xFF065F46)
val RedVibrant = Color(0xFFEF4444)
val OrangeVibrant = Color(0xFFF97316)
val AmberVibrant = Color(0xFFF59E0B)
val PurpleVibrant = Color(0xFFA855F7)
val BlueVibrant = Color(0xFF3B82F6)

val ScoreGreen = Color(0xFF10B981)
val ScoreOrange = Color(0xFFF59E0B)
val ScoreRed = Color(0xFFEF4444)

val GradientStart = Color(0xFF14B8A6)
val GradientMid = Color(0xFF0EA5E9)
val GradientEnd = Color(0xFF7C3AED)

internal val LightPrimary = Color(0xFF0D9488)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFCCFBF1)
internal val LightOnPrimaryContainer = Color(0xFF022C22)
internal val LightSecondary = Color(0xFF7E22CE)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFF3E8FF)
internal val LightOnSecondaryContainer = Color(0xFF2E1065)
internal val LightTertiary = Color(0xFF0284C7)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFE0F2FE)
internal val LightOnTertiaryContainer = Color(0xFF0C4A6E)
internal val LightError = Color(0xFFDC2626)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFEE2E2)
internal val LightOnErrorContainer = Color(0xFF450A0A)
internal val LightBackground = Color(0xFFF8FAFC)
internal val LightOnBackground = Color(0xFF0F172A)
internal val LightSurface = Color(0xFFF8FAFC)
internal val LightOnSurface = Color(0xFF0F172A)
internal val LightOnSurfaceVariant = Color(0xFF475569)
internal val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val LightSurfaceContainerLow = Color(0xFFF1F5F9)
internal val LightSurfaceContainer = Color(0xFFECF0F6)
internal val LightSurfaceContainerHigh = Color(0xFFE2E8F0)
internal val LightSurfaceContainerHighest = Color(0xFFD6DEE9)
internal val LightSurfaceDim = Color(0xFFD6DEE9)
internal val LightSurfaceBright = Color(0xFFF8FAFC)
internal val LightOutline = Color(0xFF94A3B8)
internal val LightOutlineVariant = Color(0xFFCBD5E1)
internal val LightInverseSurface = Color(0xFF1E293B)
internal val LightInverseOnSurface = Color(0xFFF8FAFC)
internal val LightInversePrimary = Color(0xFF5EEAD4)

internal val DarkPrimary = Color(0xFF5EEAD4)
internal val DarkOnPrimary = Color(0xFF00382C)
internal val DarkPrimaryContainer = Color(0xFF005140)
internal val DarkOnPrimaryContainer = Color(0xFF83F5DF)
internal val DarkSecondary = Color(0xFFD8B4FE)
internal val DarkOnSecondary = Color(0xFF3B0764)
internal val DarkSecondaryContainer = Color(0xFF581C87)
internal val DarkOnSecondaryContainer = Color(0xFFE9D5FF)
internal val DarkTertiary = Color(0xFF7DD3FC)
internal val DarkOnTertiary = Color(0xFF013343)
internal val DarkTertiaryContainer = Color(0xFF014B64)
internal val DarkOnTertiaryContainer = Color(0xFFB6ECFF)
internal val DarkError = Color(0xFFFCA5A5)
internal val DarkOnError = Color(0xFF450A0A)
internal val DarkErrorContainer = Color(0xFF7F1D1D)
internal val DarkOnErrorContainer = Color(0xFFFECACA)
internal val DarkBackground = Color(0xFF030712)
internal val DarkOnBackground = Color(0xFFF1F5F9)
internal val DarkSurface = Color(0xFF030712)
internal val DarkOnSurface = Color(0xFFF1F5F9)
internal val DarkOnSurfaceVariant = Color(0xFF94A3B8)
internal val DarkSurfaceContainerLowest = Color(0xFF010408)
internal val DarkSurfaceContainerLow = Color(0xFF0F172A)
internal val DarkSurfaceContainer = Color(0xFF172033)
internal val DarkSurfaceContainerHigh = Color(0xFF1E293B)
internal val DarkSurfaceContainerHighest = Color(0xFF263348)
internal val DarkSurfaceDim = Color(0xFF030712)
internal val DarkSurfaceBright = Color(0xFF1E293B)
internal val DarkOutline = Color(0xFF475569)
internal val DarkOutlineVariant = Color(0xFF1E293B)
internal val DarkInverseSurface = Color(0xFFF1F5F9)
internal val DarkInverseOnSurface = Color(0xFF0F172A)
internal val DarkInversePrimary = Color(0xFF0D9488)
